import type { Metadata } from "next";
import { Plus_Jakarta_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const mono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Modivi Group",
    template: "%s | Modivi Group"
  },
  description: "Modivi Group blends cutting-edge technology with creative vision to deliver digital marketing, web development, and branding solutions that grow your business.",
  keywords: [
    // Core Services - "Needed" Variations
    "web designer needed Boston",
    "web developer needed Massachusetts",
    "logo designer needed",
    "graphic designer needed Boston",
    "digital marketer needed",
    "SEO expert needed Boston",
    "social media manager needed",
    "content creator needed Massachusetts",
    "brand designer needed",
    "website developer needed",
    "marketing agency needed Boston",
    "web design company needed",
    "advertising agency needed",
    "creative agency needed Boston",
    "branding expert needed",
    
    // Web Design & Development
    "web design Boston",
    "web development Massachusetts",
    "website design services Boston",
    "custom website design",
    "responsive web design Boston",
    "mobile website design",
    "ecommerce website design Boston",
    "WordPress developer Boston",
    "web design company Boston",
    "affordable web design Massachusetts",
    "professional web design",
    "small business website design Boston",
    "website redesign services",
    "landing page design Boston",
    "website builder Boston",
    "web design agency Massachusetts",
    "website development company",
    "web designer near me",
    "local web designer Boston",
    "website maintenance Boston",
    
    // SEO Services
    "SEO services Boston",
    "local SEO Boston",
    "SEO company Massachusetts",
    "search engine optimization Boston",
    "SEO expert Boston",
    "SEO consultant Massachusetts",
    "organic SEO Boston",
    "technical SEO services",
    "on-page SEO Boston",
    "off-page SEO services",
    "keyword research Boston",
    "SEO audit services",
    "Google ranking services Boston",
    "SEO agency Massachusetts",
    "affordable SEO Boston",
    "small business SEO",
    "local search optimization",
    "SEO specialist Boston",
    "enterprise SEO services",
    "national SEO services",
    
    // Branding & Design
    "branding agency Boston",
    "brand identity design Massachusetts",
    "logo design Boston",
    "logo designer Massachusetts",
    "graphic design services Boston",
    "brand strategy Boston",
    "rebranding services Massachusetts",
    "corporate branding Boston",
    "brand development",
    "visual identity design Boston",
    "business card design",
    "brand guidelines Boston",
    "logo creation services",
    "custom logo design Boston",
    "affordable logo design",
    "professional branding Massachusetts",
    "brand consultant Boston",
    "creative branding services",
    
    // Digital Marketing
    "digital marketing agency Boston",
    "digital marketing services Massachusetts",
    "online marketing Boston",
    "internet marketing Massachusetts",
    "marketing company Boston",
    "digital advertising Boston",
    "marketing consultant Massachusetts",
    "digital strategy Boston",
    "marketing services near me",
    "full-service marketing agency",
    "integrated marketing Boston",
    "digital marketing consultant",
    "marketing solutions Massachusetts",
    "online advertising Boston",
    "digital media marketing",
    
    // Social Media
    "social media marketing Boston",
    "social media management Massachusetts",
    "social media advertising Boston",
    "Facebook ads Boston",
    "Instagram marketing Massachusetts",
    "TikTok marketing Boston",
    "social media strategy",
    "social media manager Boston",
    "content marketing Boston",
    "social media consultant Massachusetts",
    "influencer marketing Boston",
    "social media agency Massachusetts",
    "YouTube marketing Boston",
    "LinkedIn marketing Massachusetts",
    
    // PPC & Advertising
    "PPC management Boston",
    "Google Ads Boston",
    "paid advertising Massachusetts",
    "PPC agency Boston",
    "Google Ads management",
    "Facebook advertising Boston",
    "display advertising Massachusetts",
    "retargeting ads Boston",
    "pay per click Boston",
    "ad campaign management",
    "conversion optimization Boston",
    "Google Ads consultant Massachusetts",
    "paid search marketing Boston",
    "remarketing services",
    
    // Lead Generation
    "lead generation services Boston",
    "lead generation company Massachusetts",
    "B2B lead generation Boston",
    "sales funnel design",
    "conversion rate optimization Boston",
    "lead nurturing services Massachusetts",
    "marketing automation Boston",
    "CRM setup services",
    "email marketing Boston",
    "lead capture systems Massachusetts",
    
    // Content Services
    "content creation Boston",
    "content marketing services Massachusetts",
    "blog writing services Boston",
    "copywriting services Massachusetts",
    "video production Boston",
    "photography services Massachusetts",
    "content strategy Boston",
    "website content writing",
    "SEO copywriting Boston",
    "professional photography Massachusetts",
    "videography services Boston",
    "commercial photography",
    
    // Business Types
    "marketing for small business Boston",
    "contractor marketing Massachusetts",
    "healthcare marketing Boston",
    "restaurant marketing Massachusetts",
    "retail marketing Boston",
    "professional services marketing",
    "trade business marketing Boston",
    "local business marketing Massachusetts",
    "startup marketing Boston",
    "franchise marketing services",
    
    // Location-Based
    "Boston digital marketing",
    "Massachusetts web design",
    "New England marketing agency",
    "Cambridge web design",
    "Somerville digital marketing",
    "Brookline branding agency",
    "Newton web development",
    "Quincy marketing services",
    "Worcester web design",
    "Springfield digital marketing",
    "Rhode Island marketing agency",
    "Connecticut web design",
    "Vermont digital marketing",
    "New Hampshire branding",
    "Maine web development",
    "New York marketing services",
    
    // Service Combinations
    "web design and SEO Boston",
    "branding and web design Massachusetts",
    "digital marketing and web development",
    "SEO and content marketing Boston",
    "social media and advertising Massachusetts",
    "logo design and branding Boston",
    "website design and marketing",
    "full-service digital agency Boston",
    
    // Problem/Solution Keywords
    "increase website traffic Boston",
    "improve Google ranking Massachusetts",
    "grow online presence Boston",
    "get more customers online",
    "boost social media engagement",
    "generate more leads Boston",
    "improve conversion rate Massachusetts",
    "build brand awareness Boston",
    "increase sales online",
    "digital transformation services",
    
    // Technology & Platforms
    "WordPress development Boston",
    "Shopify design Massachusetts",
    "WooCommerce development Boston",
    "React web development",
    "custom web applications Boston",
    "mobile app design Massachusetts",
    "ecommerce solutions Boston",
    "CMS development",
    "API integration services Boston",
    "web hosting services Massachusetts",
    
    // Specific Services
    "Google Business Profile optimization",
    "online reputation management Boston",
    "review management services Massachusetts",
    "citation building Boston",
    "directory listings management",
    "local listings optimization Boston",
    "business profile setup Massachusetts",
    "review generation services",
    
    // Agency Types
    "creative agency Boston",
    "advertising agency Massachusetts",
    "design agency Boston",
    "media agency Massachusetts",
    "growth marketing agency Boston",
    "performance marketing agency",
    "boutique marketing agency Boston",
    "strategic marketing firm Massachusetts",
    
    // Musicians & Music Industry
    "musician marketing",
    "music marketing services",
    "artist branding",
    "musician branding Boston",
    "music promotion services",
    "independent artist marketing",
    "music PR services",
    "band marketing Boston",
    "singer marketing Massachusetts",
    "rapper marketing services",
    "hip hop marketing Boston",
    "music artist branding",
    "musician social media management",
    "music social media marketing",
    "Spotify promotion",
    "playlist placement services",
    "music playlist promotion",
    "Spotify marketing",
    "Apple Music promotion",
    "SoundCloud promotion",
    "music streaming promotion",
    "music video promotion",
    "YouTube music promotion",
    "music marketing agency",
    "artist management services",
    "music business consulting",
    "EPK design for musicians",
    "electronic press kit design",
    "musician website design",
    "band website design Boston",
    "artist portfolio website",
    "music producer marketing",
    "beat maker promotion",
    "music producer branding",
    "recording artist marketing",
    "unsigned artist marketing",
    "emerging artist promotion",
    "local musician marketing Boston",
    "music tour promotion",
    "concert promotion services",
    "music event marketing",
    "album release marketing",
    "single release promotion",
    "music launch strategy",
    "artist brand identity",
    "musician logo design",
    "band logo design",
    "music brand development",
    "artist merchandise design",
    "album cover design",
    "music graphics design",
    "music content creation",
    "musician photography",
    "artist photoshoot Boston",
    "music video production Boston",
    "music video editing",
    "lyric video creation",
    "music visualizer design",
    "artist bio writing",
    "music press release writing",
    "music blog outreach",
    "music influencer marketing",
    "TikTok music promotion",
    "Instagram music marketing",
    "YouTube music channel growth",
    "music fan engagement",
    "artist email marketing",
    "music newsletter services",
    "music analytics services",
    "streaming analytics tracking",
    
    // DJs & Electronic Music
    "DJ marketing",
    "DJ branding services",
    "DJ logo design",
    "DJ website design Boston",
    "DJ social media management",
    "DJ promotion services",
    "club DJ marketing",
    "mobile DJ marketing Massachusetts",
    "wedding DJ marketing",
    "DJ press kit design",
    "DJ portfolio website",
    "electronic music marketing",
    "EDM marketing services",
    "DJ mix promotion",
    "SoundCloud DJ promotion",
    "Mixcloud promotion",
    "DJ photography services",
    "DJ video content creation",
    "DJ brand identity",
    "nightclub marketing Boston",
    "music venue marketing",
    "DJ event promotion",
    "DJ booking services",
    "DJ management services",
    
    // Streamers & Content Creators
    "streamer marketing",
    "Twitch streamer marketing",
    "YouTube streamer promotion",
    "streamer branding services",
    "gaming content creator marketing",
    "streamer social media management",
    "Twitch channel growth",
    "stream promotion services",
    "content creator branding Boston",
    "streamer logo design",
    "Twitch logo design",
    "gaming logo design",
    "streamer brand identity",
    "content creator website design",
    "streamer portfolio website",
    "gaming website design Boston",
    "stream graphics design",
    "Twitch overlay design",
    "stream package design",
    "emote design services",
    "Twitch emote artist",
    "sub badge design",
    "stream alerts design",
    "panel design Twitch",
    "stream branding package",
    "gaming brand design",
    "esports branding",
    "gaming team branding Boston",
    "streamer merchandise design",
    "gaming merch design",
    
    // Video Editing & Clipping
    "video clipping services",
    "stream highlights editing",
    "Twitch clip editor",
    "YouTube clip creation",
    "gaming video editing",
    "stream VOD editing",
    "highlight reel creation",
    "montage video editing",
    "gaming montage services",
    "clip compilation services",
    "short form video editing",
    "TikTok video editing for streamers",
    "YouTube Shorts editing",
    "Instagram Reels editing for creators",
    "vertical video editing",
    "stream recap videos",
    "best moments editing",
    "clutch clip editing",
    "gameplay editing services",
    "content repurposing for streamers",
    "multi-platform content creation",
    "stream to YouTube conversion",
    "VOD to shorts editing",
    
    // YouTubers & Video Creators
    "YouTuber marketing",
    "YouTube channel growth services",
    "YouTube SEO services",
    "video SEO optimization",
    "YouTube channel management",
    "YouTuber social media management",
    "YouTube content strategy",
    "YouTuber branding services",
    "YouTube logo design",
    "channel art design",
    "YouTube banner design",
    "YouTube intro design",
    "YouTube outro design",
    "thumbnail design services",
    "custom thumbnail design",
    "clickable thumbnail creation",
    "YouTube graphics design",
    "video editor for YouTubers",
    "YouTube video editing services",
    "vlog editing services",
    "talking head video editing",
    "tutorial video editing",
    "educational content editing",
    "YouTube Shorts creator",
    "short form content strategy",
    "YouTube audience growth",
    "subscriber growth services",
    "view optimization services",
    "YouTube analytics consulting",
    "channel audit services",
    "YouTube monetization help",
    "creator partnership support",
    "brand deal negotiation",
    "sponsorship acquisition services",
    "influencer marketing for creators",
    "creator brand partnerships Boston",
    
    // Social Media for Creators
    "social media for musicians",
    "social media for DJs",
    "social media for streamers",
    "social media for YouTubers",
    "creator social media strategy",
    "TikTok for musicians",
    "Instagram for artists",
    "Twitter for streamers",
    "Discord community management",
    "community management for creators",
    "fan engagement services",
    "creator audience building",
    "cross-platform content strategy",
    "multi-channel creator marketing",
    
    // Content Creation Services
    "content creation for musicians",
    "content creation for streamers",
    "social content for artists",
    "behind the scenes content",
    "BTS video production",
    "studio session photography",
    "gaming content photography",
    "creator lifestyle photography",
    "podcast editing for musicians",
    "podcast production services",
    "audio editing services",
    "voice over editing",
    
    // Management & Business
    "artist management digital services",
    "creator business consulting",
    "musician career development",
    "streamer career growth",
    "YouTuber business strategy",
    "creator monetization strategy",
    "digital presence for artists",
    "online brand for musicians",
    "digital identity for creators",
    "personal brand for artists Boston",
    "influencer brand development",
    
    // Industry Specific
    "music industry marketing Boston",
    "entertainment marketing Massachusetts",
    "artist development services",
    "talent marketing services",
    "performer marketing Boston",
    "creative talent branding",
    "entertainment social media",
    "music business services Boston",
    "digital services for artists",
    "creator economy services",
    "influencer services Boston",
    "content creator agency Massachusetts",
    "music marketing agency Boston",
    "streamer management agency",
    "YouTube channel agency",
    "talent management digital services"
  ],
  authors: [{ name: "Modivi Group" }],
  creator: "Modivi Group",
  publisher: "Modivi Group",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://modivi.group"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://modivi.group",
    siteName: "Modivi Group",
    title: "Modivi Group | Digital Marketing, Web Design & Branding Agency Boston MA",
    description: "Modivi Group blends cutting-edge technology with creative vision to deliver digital marketing, web development, and branding solutions that grow your business.",
    images: [
      {
        url: "/assets/Banner.PNG",
        width: 1200,
        height: 630,
        alt: "Modivi Group - Digital Marketing & Web Design Agency",
        type: "image/png",
      }
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@modivigroup",
    creator: "@modivigroup",
    title: "Modivi Group | Digital Marketing, Web Design & Branding Agency Boston MA",
    description: "Modivi Group blends cutting-edge technology with creative vision to deliver digital marketing, web development, and branding solutions that grow your business.",
    images: ["/assets/Banner.PNG"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/assets/MG.PNG", sizes: "any" },
      { url: "/assets/MG.PNG", sizes: "32x32", type: "image/png" },
      { url: "/assets/MG.PNG", sizes: "16x16", type: "image/png" },
    ],
    apple: [
      { url: "/assets/MG.PNG", sizes: "180x180", type: "image/png" },
    ],
    shortcut: "/assets/MG.PNG",
  },
  manifest: "/manifest.json",
  verification: {
    google: "google-site-verification-code-here",
    yandex: "yandex-verification-code-here",
    yahoo: "yahoo-verification-code-here",
  },
  category: "Digital Marketing",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ProfessionalService",
              "@id": "https://modivi.group",
              "name": "Modivi Group",
              "alternateName": "MODIVI GROUP",
              "url": "https://modivi.group",
              "logo": "https://modivi.group/assets/MG.PNG",
              "image": "https://modivi.group/assets/Banner.PNG",
              "description": "Modivi Group blends cutting-edge technology with creative vision to deliver digital marketing, web development, and branding solutions that grow your business.",
              "email": "admin@modivi.group",
              "address": {
                "@type": "PostalAddress",
                "addressLocality": "Boston",
                "addressRegion": "MA",
                "addressCountry": "US"
              },
              "areaServed": [
                {
                  "@type": "State",
                  "name": "Massachusetts"
                },
                {
                  "@type": "State",
                  "name": "Connecticut"
                },
                {
                  "@type": "State",
                  "name": "Rhode Island"
                },
                {
                  "@type": "State",
                  "name": "Vermont"
                },
                {
                  "@type": "State",
                  "name": "New Hampshire"
                },
                {
                  "@type": "State",
                  "name": "Maine"
                },
                {
                  "@type": "State",
                  "name": "New York"
                }
              ],
              "geo": {
                "@type": "GeoCoordinates",
                "latitude": "42.3601",
                "longitude": "-71.0589"
              },
              "priceRange": "$$",
              "openingHours": "Mo-Fr 09:00-18:00",
              "sameAs": [
                "https://www.instagram.com/modivi.group/",
                "https://www.tiktok.com/@modivi.group",
                "https://www.youtube.com/@ModiviGroup",
                "https://x.com/modivigroup"
              ],
              "serviceType": [
                "Digital Marketing",
                "Web Design",
                "Web Development",
                "Brand Identity Design",
                "SEO Services",
                "Social Media Marketing",
                "Logo Design",
                "Lead Generation",
                "Content Creation",
                "Local SEO",
                "Search Engine Optimization",
                "PPC Management",
                "Google Ads Management",
                "Facebook Advertising",
                "Instagram Marketing",
                "TikTok Marketing",
                "YouTube Marketing",
                "LinkedIn Marketing",
                "Email Marketing",
                "Marketing Automation",
                "Conversion Rate Optimization",
                "Landing Page Design",
                "Ecommerce Website Design",
                "WordPress Development",
                "Custom Web Applications",
                "Mobile Website Design",
                "Responsive Web Design",
                "Website Redesign",
                "Website Maintenance",
                "Graphic Design",
                "Branding Strategy",
                "Corporate Branding",
                "Rebranding Services",
                "Visual Identity Design",
                "Brand Guidelines",
                "Business Card Design",
                "Copywriting",
                "Content Marketing",
                "Blog Writing",
                "SEO Copywriting",
                "Video Production",
                "Photography Services",
                "Commercial Photography",
                "Videography",
                "Keyword Research",
                "Technical SEO",
                "On-Page SEO",
                "Off-Page SEO",
                "Link Building",
                "Local Search Optimization",
                "Google Business Profile Optimization",
                "Citation Building",
                "Review Management",
                "Online Reputation Management",
                "Social Media Management",
                "Social Media Advertising",
                "Content Strategy",
                "Influencer Marketing",
                "Display Advertising",
                "Retargeting Campaigns",
                "Remarketing Services",
                "B2B Marketing",
                "B2C Marketing",
                "Startup Marketing",
                "Small Business Marketing",
                "Enterprise Marketing",
                "Franchise Marketing",
                "Healthcare Marketing",
                "Restaurant Marketing",
                "Retail Marketing",
                "Contractor Marketing",
                "Professional Services Marketing",
                "CRM Setup",
                "Sales Funnel Design",
                "Marketing Analytics",
                "Web Analytics",
                "Performance Tracking",
                "A/B Testing",
                "User Experience Design",
                "UI/UX Design",
                "Website Optimization",
                "Mobile App Design",
                "Shopify Development",
                "WooCommerce Development",
                "Ecommerce Solutions",
                "API Integration",
                "Web Hosting Services",
                "Domain Management",
                "SSL Certificate Setup",
                "Website Security",
                "Speed Optimization",
                "Digital Strategy Consulting",
                "Marketing Consulting",
                "Brand Consulting",
                "Growth Marketing",
                "Performance Marketing",
                "Integrated Marketing",
                "Omnichannel Marketing",
                "Customer Acquisition",
                "Customer Retention Marketing",
                "Lifecycle Marketing",
                "Music Marketing",
                "Artist Branding",
                "Musician Marketing",
                "Band Marketing",
                "Music Promotion",
                "Spotify Promotion",
                "Playlist Placement",
                "Music Streaming Promotion",
                "Artist Management",
                "Music Business Consulting",
                "EPK Design",
                "Electronic Press Kit",
                "Musician Website Design",
                "Artist Portfolio Website",
                "Music Producer Marketing",
                "Album Release Marketing",
                "Music Video Production",
                "Music Video Editing",
                "Lyric Video Creation",
                "Artist Photography",
                "Music Content Creation",
                "Music Press Release Writing",
                "Music Influencer Marketing",
                "TikTok Music Promotion",
                "YouTube Music Promotion",
                "DJ Marketing",
                "DJ Branding",
                "DJ Logo Design",
                "DJ Website Design",
                "DJ Social Media Management",
                "DJ Promotion",
                "DJ Press Kit Design",
                "Electronic Music Marketing",
                "EDM Marketing",
                "DJ Mix Promotion",
                "DJ Event Promotion",
                "Streamer Marketing",
                "Twitch Marketing",
                "YouTube Streamer Promotion",
                "Streamer Branding",
                "Gaming Content Creator Marketing",
                "Twitch Channel Growth",
                "Stream Promotion",
                "Content Creator Branding",
                "Streamer Logo Design",
                "Gaming Logo Design",
                "Stream Graphics Design",
                "Twitch Overlay Design",
                "Emote Design",
                "Stream Package Design",
                "Gaming Brand Design",
                "Esports Branding",
                "Streamer Merchandise Design",
                "Video Clipping Services",
                "Stream Highlights Editing",
                "Twitch Clip Editing",
                "YouTube Clip Creation",
                "Gaming Video Editing",
                "Stream VOD Editing",
                "Highlight Reel Creation",
                "Montage Video Editing",
                "Short Form Video Editing",
                "TikTok Video Editing",
                "YouTube Shorts Editing",
                "Instagram Reels Editing",
                "Content Repurposing",
                "YouTuber Marketing",
                "YouTube Channel Growth",
                "YouTube SEO",
                "Video SEO Optimization",
                "YouTube Channel Management",
                "YouTube Content Strategy",
                "YouTuber Branding",
                "Channel Art Design",
                "YouTube Banner Design",
                "YouTube Intro Design",
                "Thumbnail Design",
                "Custom Thumbnail Design",
                "YouTube Video Editing",
                "Vlog Editing",
                "Tutorial Video Editing",
                "YouTube Shorts Creation",
                "Subscriber Growth Services",
                "YouTube Analytics Consulting",
                "YouTube Monetization Support",
                "Brand Deal Negotiation",
                "Sponsorship Acquisition",
                "Influencer Marketing for Creators",
                "Creator Brand Partnerships",
                "Social Media for Musicians",
                "Social Media for DJs",
                "Social Media for Streamers",
                "Social Media for YouTubers",
                "Creator Social Media Strategy",
                "Discord Community Management",
                "Community Management for Creators",
                "Fan Engagement Services",
                "Audience Building for Creators",
                "Cross-Platform Content Strategy",
                "Behind the Scenes Content",
                "Studio Session Photography",
                "Gaming Content Photography",
                "Podcast Editing for Musicians",
                "Podcast Production",
                "Audio Editing Services",
                "Artist Management Digital Services",
                "Creator Business Consulting",
                "Musician Career Development",
                "Streamer Career Growth",
                "YouTuber Business Strategy",
                "Creator Monetization Strategy",
                "Digital Presence for Artists",
                "Personal Brand for Artists",
                "Influencer Brand Development",
                "Music Industry Marketing",
                "Entertainment Marketing",
                "Artist Development Services",
                "Talent Marketing",
                "Performer Marketing",
                "Creative Talent Branding",
                "Entertainment Social Media",
                "Creator Economy Services",
                "Influencer Services",
                "Content Creator Agency Services",
                "Streamer Management",
                "YouTube Channel Agency Services",
                "Talent Management Digital Services"
              ],
              "hasOfferCatalog": {
                "@type": "OfferCatalog",
                "name": "Digital Marketing Services",
                "itemListElement": [
                  {
                    "@type": "Offer",
                    "itemOffered": {
                      "@type": "Service",
                      "name": "Brand Identity Design",
                      "description": "Create a cohesive visual identity that resonates with your target audience and stands out in your industry."
                    }
                  },
                  {
                    "@type": "Offer",
                    "itemOffered": {
                      "@type": "Service",
                      "name": "Web Development",
                      "description": "Modern, responsive websites that convert visitors into customers with seamless user experiences."
                    }
                  },
                  {
                    "@type": "Offer",
                    "itemOffered": {
                      "@type": "Service",
                      "name": "Digital Marketing",
                      "description": "Data-driven marketing strategies that increase visibility and drive qualified leads to your business."
                    }
                  },
                  {
                    "@type": "Offer",
                    "itemOffered": {
                      "@type": "Service",
                      "name": "Lead Generation",
                      "description": "Automated systems that capture, nurture, and convert leads while you focus on your craft."
                    }
                  },
                  {
                    "@type": "Offer",
                    "itemOffered": {
                      "@type": "Service",
                      "name": "Local SEO",
                      "description": "Dominate local search results and become the go-to choice in your area."
                    }
                  },
                  {
                    "@type": "Offer",
                    "itemOffered": {
                      "@type": "Service",
                      "name": "Content Creation",
                      "description": "Consistent, high-quality content that keeps your brand top-of-mind and builds authority."
                    }
                  }
                ]
              }
            })
          }}
        />
        <meta name="theme-color" content="#000000" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>
      <body
        className={`${jakarta.variable} ${mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
